### ISSUE TITLE
Search Failed

### ISSUE THREAD

**Issue by Harrisonkamau** [dmmuchoki7/phase-1-project#1]
@MuchokiDavid I'm a big fan of this series! However, trying to search for a fugitive by their name fails. Check out the screenshot below. Hint: validate your `data` responses.

<img width="1321" alt="Screenshot 2024-02-26 at 21 04 04" src="https://github.com/MuchokiDavid/FBI_most_wanted/assets/15138152/e53392a2-d598-4583-8847-65c27650a7e2">

**Comment by MuchokiDavid** [comment]
Let me check it out. It was working earier

**Comment by MuchokiDavid** [comment]
Have tested it and it is searching, maybe you can reload the app and try to search again

**Comment by Harrisonkamau** [comment]
You're right. It's working on Chrome. But fails on Safari.

**Comment by Harrisonkamau** [comment]
Good job 🎉

**Comment by MuchokiDavid** [comment]
Thanks
